### PR TITLE
Adding adding vl-convert-rs Rustler wrapper

### PR DESCRIPTION
**Pull request by akoutmos**
This PR addresses #80. Still a work in progress but figured I would open this up anyways in case there are any red flags while I am working on this.

### CODE REVIEW

**Comment by jonatanklosko** [comment]
Hey @akoutmos, thanks working on this! Quick question, what is the size of the NIFs?

Since vl_convert embeds a whole JS runtime, it may be more sensible to make this opt-in through some means. One option would be an optional dependency `:vega_lite_convert`, but the public API can still be `VegaLite.Export`, we would just raise if it's missing. My main reasoning is that many users using VegaLite in Livebook, may not need to export, since the results are rendered (and can actually be exported via the UI). Another benefit of an optional dependency is that it could depend on `:jason`, so it would be optional as well. @josevalim wdyt?

**Comment by akoutmos** [comment]
Thanks for the quick feedback @jonatanklosko! At the moment we're looking at about 112MB for the compiled `libex_vl_convert.so` file which is indeed pretty chunky.

I'm onboard with moving all of the NIF related bits to a separate `:vega_lite_convert` library so that we don't have to download artifacts needlessly given this feature is only useful in a handful of scenarios.

**Comment by josevalim** [comment]
I agree on vega_lite_convert as a dependency, given the size of the binary, but how would you tackle the API, @jonatanklosko? Should we tell people to use VegaLite.Converter in the future and that depends on VegaLite instead?

**Comment by jonatanklosko** [comment]
@josevalim changing `VegaLite.Export` would be a breaking change, the API is the same, but the dependencies change. So I agree that putting the new code in `VegaLite.Converter` sounds best, and we deprecate everything in `VegaLite.Export`.

The remaining question is `VegaLite.Viewer.{show,show_and_wait}` which depends on `to_html` (the current implementation of which requires `:jason`). I am thinking, let's deprecate that also, and have `VegaLite.Converter.{open_viewer,open_viewer_wait}` (names debatable). How does that sound?

**Comment by josevalim** [comment]
Sounds good to me!

**Comment by jonatanklosko** [comment]
@akoutmos I created [livebook-dev/vega_lite_convert](https://github.com/livebook-dev/vega_lite_convert), please open a PR there. Once we are ready there, I will do all the necessary deprecations!

**Comment by akoutmos** [comment]
Thanks for the feedback @josevalim & @jonatanklosko! I'll start moving things over to the new repo tomorrow as today is a bit swamped.

**Comment by pnezis** [comment]
@jonatanklosko @akoutmos it seems that there already exists a [`vega_lite_convert`](https://hex.pm/packages/vega_lite_convert) package.

**Comment by jonatanklosko** [comment]
@pnezis oh, thank you for the heads up! I see the package only exposes a single function and we would cover that use case. I will contact the maintainer to see if we can unify :)

**Pull request closed without merging**
